### ISSUE TITLE
Creating a new staff crashes

### ISSUE THREAD

**Issue by jean2048** [squoshi/irons_spells_js#5]
[crash-2024-05-26_10.36.36-client.txt](https://github.com/squoshi/irons_spells_js/files/15464489/crash-2024-05-26_10.36.36-client.txt)

**Comment by sentwayfarer** [comment]
Are you able to send your latest.log file? I'm not getting enough information from this crash log. Preferably also send your code.

**Comment by jean2048** [comment]
Do you have a place to communicate, such as Discord? It seems to be very difficult to communicate in this way

**Comment by jean2048** [comment]
And I directly copied your code for testing, which resulted in a crash

**Comment by sentwayfarer** [comment]
> Do you have a place to communicate, such as Discord? It seems to be very difficult to communicate in this way

Ideally in the KubeJS discord: https://discord.gg/lat
Create a support post there and ping me with it. My Discord username is the same as my GitHub username, but with a period at the end.

**Comment by sentwayfarer** [comment]
Any news? I haven't seen you join the Discord.

**Comment by sentwayfarer** [comment]
User error, no need for fixes
